### ISSUE TITLE
No Error With Expected Return Not Present

### ISSUE THREAD

**Issue by Caleb-o** [pepplejoshua/proto#24]
## Description
If adding a return type, you can omit the return and it will compile without error. This causes a warning in the C++ compiler, which then crashes when running the executable.

## Expected Behaviour
This can go two ways:
1. A default value returned when omitted
2. Error thrown at compile-time, that expects a return to be present when a type is specified.

## Examples
```rs
fn get_value() int {}

fn main() int {
    bad_value :: get_value();
}
```

Another version, that conditionally returns also results in the same issue:
```rs
fn get_value(maybe bool) int {
    if maybe {
        return 1;
    }
}

fn main() int {
    bad_value :: get_value(false);
}
```

**Comment by pepplejoshua** [comment]
Fixed bug in: [Commit 1](https://github.com/pepplejoshua/proto/commit/22cfd81c864e96e22cfc3b1b0daa4ffc4e73c586) and [Commit 2](https://github.com/pepplejoshua/proto/commit/95d18b8b1038b102d8f2f654dc38836947ad6756).
